platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

target "MQTTTest"
pod 'MQTTClient'

target "FlexLib"
pod 'FlexLib'

target "ReactiveCocoa"
pod 'ReactiveObjC'

target "ControllerAnimation"
pod 'lottie-ios', '~> 2.5.3'

