#ifndef Demo_codeObfuscation_h
#define Demo_codeObfuscation_h
//confuse string at Mon Jan  7 18:39:11 CST 2019
#define playerItemDidReachEnd NJgJuLMwjTAlMgQb
#define panPlayer VYoeYqWDQkZpXRHp
#define buildUI dvfDNJhQsBabZwGf
#define tips DpxMEVnHzKVAppWZ
#define rotate WPBfuWXOLAEjYesk
#define crop GYlGGmfAAoRjrbGp
#define back BfLYlHOGMEnQKuGY
#define dismissClick cyGryysuUQrgrHcv
#define doubleTap qvrpQQgnYlIpnCZP
#define imageFromView veplGtqvZDjZWqzz
#define atFrame gOudoZTqXZWuNyou
#define parameter vchawzXxswfsnKHc
#define hud HaMyrorBbsbYuNiF
#define previewDidNextClick CGAGdjvGirKJFiep
#define didNextClick vyuZhxdZAvdMFPmG
#define rightBtn cpRbAtqmIvFZOLog
#define leftBtn OVjnYBgnxLAhGMCw
#define imageUploadFromClip vCyxReYbpWDjszKj
#define clipImage nmCVWNipLyhAjLQG
#define success xinXPJZthAqiIoum
#define result cfXUphUwfkkOAVVv
#define originPath VjRYKZGMgXgQpcpi
#define clipPath YywQweVXsiaJpiJj
#define pushEdit JZFICFOZwzYNkKlt
#define mixUploadFromAlbumPreview wPLsTDWRyRloyxXx
#define source ckwlWuAnOVMhRhFD
#define imageUploadFromVideo jAyekBfZikwPbdTv
#define clipImage WFuFAQTHIqdScTAs
#define videoPreviewUpload hdEyliJsJzIPKDcv
#define previewUpload RIIUgCaEweMYaEiF
#define source PdbayLUZpdNhWffP
#define imageUploadFromPhoto AmMpquZnehRAwbGU
#define clipImage grxotLngrIoOgybp
#define changeButtonClick AZgkmGCHQxbcJWTP
#define cellChangeLivePhotoState LBGwWVlqPXSmKykn
#define allPreviewdidSelectedClick GzXBiFqyumBkpOZn
#define didTableViewCellClick iDQQHinhYomTfqZC
#define cameraDidNextClick KRfqQcZDhEczIFud
#define fullScreenCameraDidNextClick vCUFxbIYrgzJolYF
#define imagePickerController vaKQNmjkGoXofKzF
#define didFinishPickingMediaWithInfo ZrMtgVqWkaPRrpcM
#define observeAuthrizationStatusChange nWeidmNDXHBvYGoQ
#define getAlbumPhotos IGGYdzmmGbDMnjrp
#define didSelectedClick kzRZGViZUqAZmFSz
#define selectClick UFUQWzGOTcnIFFAh
#define systemPhotoDidChange cUDMKDAiBgvAKkxl
#define setupNavRightBtn WdXojlRaWzZqdKtU
#define cameraSwitch iajdtVwGYPIqEFXa
#define recaptureButton VvXjEHVWiykWPqYn
#define progressLayer fnuxILBOoXBgCMQl
#define focusLayer XNddGfQrRKZIVDQS
#define commitButton HyanMAQLeXZPkwIM
#define videoSettings XOBMTQFltmFnIuVr
#define audioSettings cQlfCPnXHOlkHWsR
#define leveBeautyFilter QCljdbNWDKtGInit
#define videoCamera spxnprwmidsOUaPn
#define updateProgress oQxJNXtupqSGFFdx
#define playing QnzxtghQqhucmUoa
#define animationCamera wsdJqgMAvrHnKFQQ
#define moviePlayDidEnd VpqwUkaAgPtQbHWa
#define animationDidStop ThenVLDDKUgpwkiZ
#define timerupdating XArngPRykqMrWPZX
#define endAllTypeRecord ELOojtjFKidtOaqO
#define beginAllTypeRecord FiNoBJzpopTnsZoA
#define cancelRecord euKWCOBEvLoPtWLI
#define endRecord piJuAmFrxrxZUEOo
#define beginRecord BYgZoTlGgxokNpUe
#define finishTakePhoto RlNvuaJtSkeGZfmV
#define beautyValueChanged FViQzKARagYrVhHS
#define uploadImage nBMZqkdizpiqzFzL
#define progress pLJBgOHOWAdOHwUV
#define uploadVideo BiVTfPSCKTUnrRCv
#define deviceOrientationChanged FwAVrpdgCCNPAZwJ
#define deviceOrientationWillChanged lDdZMJbsGmXgztDx
#define cancelDispatchTimer WNOZkoBVjPzdfayc
#define createDispatchTimerTimeInterval UjRYoQHoSyweHdic
#define repeats wipZcOjYMkfXtcSR
#define action lRAMcSMHnWrrvVMs
#define scheduledDispatchTimerTimeInterval bMcDITigyaZsHsdS
#define callBlockNow igKdJgKKwgkLlcaf
#define folderSizeAtPath DAIiRdKgyidrPfgd
#define fileSizeAtPath ZYSqlNNKiyKyktTw
#define userDirPath oCEMwmwQMkUPFxpS
#define creatDirPath scrrKVmMQiAENWpi
#define documentsPath yeyBCOPTlaNbKqhF
#define libraryPath SCaNxvqjwdwpYOkc
#define cachesPath RIbcfUczswFEpeGH
#define tempPath YRGKjXIUtBbiXPao
#define load zfqhgIxUCNBtoqhz
#define updateData GLCXhtGjQbnoaiUw
#define forService iSSSGWJMvmPoIjIo
#define getKeychainQuery KjCBXwAiBTvlWWtl
#define saveUUid sgIBSvoUXnXNKGUY
#define UUId VHvPhQkbeOLqbnkb
#define convertVideo SkNjdZfYvLEhpnLX
#define finished wlGOeGvheyepihcL
#define videoQuality nExcGkiFUzzvTMwc
#define convertAsset CFBoFEnEUfMidvXh
#define fetchImage DfvdVbPNHxRkUqKk
#define image gxuSnPBjGLEqIMEr
#define fetchImages nkfwULEPlZTQdbrV
#define images XbkXgVHCizwNgLGE
#define browserViewWillClose JQJiRjtoZHvoGYtq
#define editPhoto WlfrYTTCkFpxcmlV
#define initWithGroupItems SAhYVaYVMUyJvNDU
#define presentFromImageView cgLHRMKTFTroOvOg
#define toContainer mGXwuipyjMlSWHOw
#define dismissAnimated HDmpTGCCYpBJZhZm
#define dismiss DEvrpAsKyfZVxCtF
#define cellScrollViewDidScroll qapGOWFknvAgYjxZ
#define cellScrollViewDidEndScroll PFUeSmhEWMSrzsRX
#define playVideo XeioNIFusCVDVonB
#define resumePlayVideo WAhIftXiFagaEkAs
#define pauseVideo YIXSADUGbWgymRWc
#define stopVideo LWXyzsRFLFKAwyIU
#define reverPlayerStatus avwUOCFIPpGMcJKH
#define resizeSubviewSize LaYxGpicWvztOvoK
#endif
